server:
  port: 8010

spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081/
          predicates:
            - Path=/api/users/**, /integration/users/**
        - id: friends
          uri: http://localhost:8082/
          predicates:
            - Path=/api/friends/**, /integration/friends/**
        - id: chat
          uri: http://localhost:8083/
          predicates:
            - Path=/api/chat/**, /integration/chat/**