spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: password
    locations: classpath:migrations
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rmq-user}
    password: ${RABBITMQ_PASSWORD:rmq-pass}
  cloud.stream.bindings:
    userNotifiedEvent-out-0:
      destination: ${app.id}_USER_EVENT_NOTIFIED
    userModifiedEvent-out-0:
      destination: ${app.id}_USER_EVENT_MODIFIED

app:
  name: User Service
  id: ${MESSENGER_APP_ID:dmitry.g}
  security: # этот набор свойств парсит SecurityProps
    jwt-token:
      permit-all:
        - /api/users/register # пример метода регистрации пользователя (нет в проекте)
        - /api/users/login
        - /api/users/list
        - /api/friends/blacklist/sync
        - /api/friends/sync
      root-path: /api
      secret: 423F4528482B4D6251655468576D5A7134743777217A25432A46294A404E6352
      expiration: 86400000 # время миллисекунд
    integrations:
      root-path: /integration
      api-key: ZcQQC76uuFdiHjLufyH7C4xibCXuGRvvILgVaERrPYBiAaDTFpsUst8nh2cnGgWvJXEXB4xaXM2RFWkWJ5TriYzAe6DwD4MJtSowZfhayfHKOwzCnvt9nmQoVi1SgnFX

integration-urls:
  check-if-blacklisted: http://localhost:8010/integration/friends/check-if-blacklisted

server:
  port: 8081