spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: password

  flyway:
    url: jdbc:postgresql://localhost:5432/user_db
    user: postgres
    password: password
    locations: classpath:migrations

server:
  port: 8080